######################################################################
# Automatically generated by qmake (3.1) Mon Mar 12 21:18:02 2018
######################################################################

#对于编译好的结果 这个很重要
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
######################

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp

HEADERS += \
    ui_gotocelldialog.h \
    gotocelldialog.h


